# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63lient.proto\x12\x02pb\"\"\n\x03\x43md\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\t\"\x10\n\x03Rsp\x12\t\n\x01r\x18\x01 \x01(\t2\'\n\x06Waiter\x12\x1d\n\x07\x45xecCmd\x12\x07.pb.Cmd\x1a\x07.pb.Rsp\"\x00\x62\x06proto3')
)




_CMD = _descriptor.Descriptor(
  name='Cmd',
  full_name='pb.Cmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pb.Cmd.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='pb.Cmd.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=54,
)


_RSP = _descriptor.Descriptor(
  name='Rsp',
  full_name='pb.Rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='r', full_name='pb.Rsp.r', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['Cmd'] = _CMD
DESCRIPTOR.message_types_by_name['Rsp'] = _RSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cmd = _reflection.GeneratedProtocolMessageType('Cmd', (_message.Message,), dict(
  DESCRIPTOR = _CMD,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:pb.Cmd)
  ))
_sym_db.RegisterMessage(Cmd)

Rsp = _reflection.GeneratedProtocolMessageType('Rsp', (_message.Message,), dict(
  DESCRIPTOR = _RSP,
  __module__ = 'client_pb2'
  # @@protoc_insertion_point(class_scope:pb.Rsp)
  ))
_sym_db.RegisterMessage(Rsp)



_WAITER = _descriptor.ServiceDescriptor(
  name='Waiter',
  full_name='pb.Waiter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=74,
  serialized_end=113,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExecCmd',
    full_name='pb.Waiter.ExecCmd',
    index=0,
    containing_service=None,
    input_type=_CMD,
    output_type=_RSP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WAITER)

DESCRIPTOR.services_by_name['Waiter'] = _WAITER

# @@protoc_insertion_point(module_scope)
