# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_pb2 as client__pb2


class WaiterStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExecCmd = channel.unary_unary(
        '/pb.Waiter/ExecCmd',
        request_serializer=client__pb2.Cmd.SerializeToString,
        response_deserializer=client__pb2.Rsp.FromString,
        )


class WaiterServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExecCmd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WaiterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExecCmd': grpc.unary_unary_rpc_method_handler(
          servicer.ExecCmd,
          request_deserializer=client__pb2.Cmd.FromString,
          response_serializer=client__pb2.Rsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.Waiter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
